### ISSUE TITLE
Format Change?

### ISSUE THREAD

**Issue by EvanButterfield** [MysteriousJ/Blender-Export-Scripting-Guide#1]
The readme file shows a file format that isn't accurate to what I can see in the file. The file actually shows that we:
`writeBool(file, armature!=0)`
`writeUint16(file, len(faces))`
`writeUint16(file, len(vertices))`
`writeFaces(file, faces)`
`writeVertices(file, vertices, armature)`

This format is a lot different than what is shown in the readme, however when trying to import the format shown above, I get garbage values. Can you update the readme or explain how to import this file because I'm not sure why this isn't working for me if it's not because of a mysterious format change

**Comment by MysteriousJ** [comment]
Thanks for pointing that out, I updated the readme.
If exporting as plain text, what are the first 3 values?
If exporting as binary, what are the first 5 bytes in the file?

**Comment by EvanButterfield** [comment]
When exporting as plain text (I'm using default cube for both examples) I get `False 12 24 0 1`. When exporting as binary I get `0`, `12`, `0`, `24`,`0`. I actually can't read the binary in right now, but I used RapidTables to grab the bytes. You can find the 2 files [here](https://drive.google.com/drive/folders/1Ts6Py2QYwj_o-g-Rd1t3juAQKLgRirFa?usp=sharing).

**Comment by MysteriousJ** [comment]
Both of those files look like reasonable data to me. What part was "garbage?"

**Comment by EvanButterfield** [comment]
Funny thing. A lil bit after this, I figured out my uint16 type was actually defined as an int32. So, the garbage values would be my fault and I'm glad you got the Readme updated
